### ISSUE TITLE
 <meta http-equiv="X-UA-Compatible" content="IE=edge">

### ISSUE THREAD

**Issue by LyndaJWilliams** [joshbuchea/HEAD#123] opened 2016-06-10 17:42 UTC
Checked this out and can't decide from what I read if it should be in a minimal HEAD recommendation in 2016.  Seems from what I read that it matters only if one is coding for IE-9 and below browsers. I teach an intro course in HTML5 which is why I am interested. 

http://stackoverflow.com/questions/6771258/whats-the-difference-if-meta-http-equiv-x-ua-compatible-content-ie-edge-e

**Comment by joshbuchea** [comment] 2016-06-10 18:00
Closing, duplicate of #121. I left a [comment](https://github.com/joshbuchea/HEAD/issues/121#issuecomment-224873084) on that thread with my reasoning for including this tag, and when I intend to drop it.

IE 10 & below was my understanding after reading the [x-ua-compatible](https://github.com/h5bp/html5-boilerplate/blob/master/dist/doc/html.md#x-ua-compatible) section of the H5BP Docs. But, I may have misunderstood.

**Closed by joshbuchea** 2016-06-10 18:00 UTC

**Comment by LyndaJWilliams** [comment] 2016-06-10 18:15
Thanks. I'm a newbie to github so apologies for not knowing to search resolved comments. I'm sure you are right, re: 9 vs 10 ... I only did a quick google.

**Comment by joshbuchea** [comment] 2016-06-10 18:50
No apology necessary @LyndaJWilliams. I apologize, my reply was a bit curt. I should have included the quoted comment so you didn't have to navigate to another issue, and I could have thrown in a :smile: or two while I was at it.

[H5BP](https://github.com/h5bp/html5-boilerplate) & [Bootstrap](https://github.com/twbs/bootstrap) are both projects I respect and look to for guidance when making decisions for HEAD. Which is why I included the tag in the minimal example. But, your point about whether the `x-ua-compatible` tag should be included in a minimal head recommendation in 2016 is valid, and is up probably up for debate.

**Comment by LyndaJWilliams** [comment] 2016-06-10 19:08
In general terms, given your rationale, I'd say it's worth including. Creates a dilemma for me as an instructor of an intro course, is all. How much advanced practice does one include when the curriculum outcomes don't touch on the topics implied? On the other hand, I am overhauling the course with an eye to plugging it into the real and evolving picture so it's something I'll ponder. Maybe give 'em the barest minimum but provide an <aside> to a good recommendation like yours. I'm learning github with the notion of building course materials where there's community to help me answer such questions. Look forward to learning a lot.

**Comment by joshbuchea** [comment] 2016-06-15 21:50
Well, welcome to GitHub @LyndaJWilliams! It's an excellent place for community & collaboration. Best of luck to you with your course design.
